#region copyright
/*
    OurPlace is a mobile learning platform, designed to support communities
    in creating and sharing interactive learning activities about the places they care most about.
    https://github.com/GSDan/OurPlace
    Copyright (C) 2018 Dan Richardson

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/
#endregion

// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using OurPlace.iOS.ViewSources;
using SafariServices;
using UIKit;

namespace OurPlace.iOS
{
    public partial class SettingsController : UITableViewController
    {
		public SettingsController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            if (TabBarController != null)
            {
                TabBarController.NavigationItem.Title = "Settings";

                TabBarController.NavigationItem.LeftBarButtonItem = null;

                TabBarController.NavigationItem.RightBarButtonItem = null;
            }
        }

		public override void ViewDidLoad()
		{
            base.ViewDidLoad();

            TableView.Source = new SettingsViewSource(this, OpenWebPage);
		}

        private void OpenWebPage(NSUrl url)
        {
            var safariController = new SFSafariViewController(url);
            PresentViewControllerAsync(safariController, true);
        }
	}
}
