#region copyright
/*
    OurPlace is a mobile learning platform, designed to support communities
    in creating and sharing interactive learning activities about the places they care most about.
    https://github.com/GSDan/OurPlace
    Copyright (C) 2018 Dan Richardson

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/
#endregion

// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using System.Threading.Tasks;
using FFImageLoading;
using Foundation;
using MobileCoreServices;
using Newtonsoft.Json;
using OurPlace.Common.Models;
using UIKit;

namespace OurPlace.iOS
{
    public partial class Create_EditInfoController : Create_EditTaskController
    {
        private string previousImage;
        private string currentImagePath;
        private string folderPath;
        private string chosenLink;
        private UIImagePickerController imagePicker;
        private UIDocumentPickerViewController docPicker;

        public Create_EditInfoController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AddImageButton.TouchUpInside += AddImageButton_TouchUpInside;

            if (!string.IsNullOrWhiteSpace(thisTask?.JsonData))
            {
                AdditionalInfoData data =
                    JsonConvert.DeserializeObject<AdditionalInfoData>(thisTask.JsonData);

                previousImage = data.ImageUrl;

                if (!string.IsNullOrWhiteSpace(previousImage))
                {
                    ImageService.Instance.LoadFile(
                    AppUtils.GetPathForLocalFile(previousImage))
                            .Into(AccompanyingImage);
                }

                if (!string.IsNullOrWhiteSpace(data.ExternalUrl))
                {
                    chosenLink = data.ExternalUrl;
                    LinkLabel.Text = data.ExternalUrl;
                }
            }

            folderPath = Common.LocalData.Storage.GetCacheFolder("created");

            UpdateLabels();

            AddLinkButton.TouchUpInside += AddLinkButton_TouchUpInside;
        }

        private void AddImageButton_TouchUpInside(object sender, EventArgs e)
        {
            UIAlertController alert = UIAlertController.Create("Choose Image Source", null, UIAlertControllerStyle.ActionSheet);
            alert.AddAction(UIAlertAction.Create("Camera", UIAlertActionStyle.Default, (a) => { OpenCamera(); }));
            alert.AddAction(UIAlertAction.Create("Gallery", UIAlertActionStyle.Default, (a) => { OpenImagePicker(); }));
            alert.AddAction(UIAlertAction.Create("Other Sources", UIAlertActionStyle.Default, (a) => { OpenDocumentPicker(); }));
            alert.AddAction(UIAlertAction.Create("Cancel", UIAlertActionStyle.Cancel, null));

            UIPopoverPresentationController popCont = alert.PopoverPresentationController;
            if (popCont != null)
            {
                popCont.SourceView = AddImageButton;
                popCont.SourceRect = AddImageButton.Bounds;
                popCont.PermittedArrowDirections = UIPopoverArrowDirection.Down;
            }

            PresentViewController(alert, true, null);
        }

        private void OpenCamera()
        {
            imagePicker = new UIImagePickerController
            {
                SourceType = UIImagePickerControllerSourceType.Camera,
                MediaTypes = new string[] { UTType.Image }
            };
            imagePicker.FinishedPickingMedia += ImagePicker_FinishedPickingMedia;
            imagePicker.Canceled += (object sender, EventArgs e) => { imagePicker.DismissViewController(true, null); };
            PresentViewController(imagePicker, true, null);
        }

        // https://github.com/xamarin/recipes/tree/master/Recipes/ios/media/video_and_photos/choose_a_photo_from_the_gallery
        private void OpenImagePicker()
        {
            imagePicker = new UIImagePickerController
            {
                SourceType = UIImagePickerControllerSourceType.PhotoLibrary,
                MediaTypes = new string[] { UTType.Image }
            };
            imagePicker.FinishedPickingMedia += ImagePicker_FinishedPickingMedia;
            imagePicker.Canceled += (object sender, EventArgs e) => { imagePicker.DismissViewController(true, null); };
            PresentViewController(imagePicker, true, null);
        }

        private void ImagePicker_FinishedPickingMedia(object sender, UIImagePickerMediaPickedEventArgs e)
        {
            bool isImage = false;
            switch (e.Info[UIImagePickerController.MediaType].ToString())
            {
                case "public.image":
                    Console.WriteLine("Image selected");
                    isImage = true;
                    break;
                case "public.video":
                    Console.WriteLine("Video selected");
                    break;
            }

            if (!isImage) return; //sanity check against video

            NSUrl referenceUrl = e.Info[new NSString("UIImagePickerControllerReferenceURL")] as NSUrl;
            UIImage passedImage = e.Info[UIImagePickerController.OriginalImage] as UIImage;

            ShrinkAndSaveNewImage(passedImage);

            imagePicker?.DismissViewController(true, null);
        }

        private void ShrinkAndSaveNewImage(UIImage passedImage)
        {
            if (passedImage == null) return;

            UIImage smallerImage = AppUtils.ScaleAndRotateImage(passedImage, 800);
            NSData imageData = smallerImage.AsJPEG(0.8f);

            if (currentImagePath == null)
            {
                currentImagePath = Path.Combine(folderPath, "task_" + DateTime.UtcNow.ToString("s") + ".jpg");
            }
            else if (!File.Exists(currentImagePath))
            {
                File.Create(currentImagePath);
            }

            // save the image data to a folder ready for uploading
            if (imageData.Save(currentImagePath, true))
            {
                Console.WriteLine("Saved photo to: " + currentImagePath);
                ImageService.Instance.InvalidateCacheEntryAsync(currentImagePath, FFImageLoading.Cache.CacheType.All, true);
                ImageService.Instance.LoadFile(currentImagePath).Into(AccompanyingImage);
            }
            else
            {
                Console.WriteLine("ERROR saving to " + currentImagePath);
            }

            UpdateLabels();
        }

        private async Task OpenDocumentPicker()
        {
            if (PresentedViewController != null)
            {
                await DismissViewControllerAsync(false);
            }

            // Allow the Document picker to select a range of document types
            var allowedUTIs = new string[] {
                UTType.PNG,
                UTType.JPEG,
                UTType.Image
            };

            // Display the picker
            docPicker = new UIDocumentPickerViewController(allowedUTIs, UIDocumentPickerMode.Import);
            docPicker.AllowsMultipleSelection = false;
            docPicker.DidPickDocumentAtUrls += DocPicker_DidPickDocumentAtUrls;

            await PresentViewControllerAsync(docPicker, false);
        }

        void DocPicker_DidPickDocumentAtUrls(object sender, UIDocumentPickedAtUrlsEventArgs e)
        {
            if (e.Urls == null || e.Urls.Length < 1) return;

            docPicker?.DismissViewControllerAsync(true);

            // IMPORTANT! You must lock the security scope before you can
            // access this file
            var securityEnabled = e.Urls[0].StartAccessingSecurityScopedResource();

            ThisApp.ClearDocumentHandler();
            ThisApp.DocumentLoaded += ThisApp_DocumentLoaded;
            ThisApp.OpenDocument(e.Urls[0]);

            // IMPORTANT! You must release the security lock established
            // above.
            e.Urls[0].StopAccessingSecurityScopedResource();
        }

        public void ThisApp_DocumentLoaded(Helpers.GenericTextDocument document)
        {
            if (currentImagePath != null && currentImagePath != previousImage)
            {
                File.Delete(AppUtils.GetPathForLocalFile(currentImagePath));
            }

            string tempPath = document.FileUrl.Path;

            UIImage fullSize = UIImage.FromFile(tempPath);

            ShrinkAndSaveNewImage(fullSize);
        }

        private void AddLinkButton_TouchUpInside(object sender, EventArgs e)
        {
            ScrollTheView(false);

            keyboardManagedElsewhere = true;

            UIAlertController alertController = UIAlertController.Create(
                "Add External Link",
                "Paste the full URL:",
                UIAlertControllerStyle.Alert);

            UITextField field = null;

            // Add and configure text field
            alertController.AddTextField((textField) =>
            {
                // Save the field
                field = textField;
                field.ReturnKeyType = UIReturnKeyType.Done;
                field.ClearButtonMode = UITextFieldViewMode.WhileEditing;

            });

            alertController.AddAction(UIAlertAction.Create("Add", UIAlertActionStyle.Default, (actionOK) =>
            {

                if (!string.IsNullOrWhiteSpace(field.Text))
                {
                    Uri uriResult;
                    bool validUrl = Uri.TryCreate(field.Text, UriKind.Absolute, out uriResult)
                        && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);

                    if (validUrl)
                    {
                        chosenLink = field.Text;
                        LinkLabel.Text = field.Text;
                        UpdateLabels();
                    }
                    else
                    {
                        AppUtils.ShowSimpleDialog(this, "Invalid URL", "The url you entered isn't valid. Please try again.", "Got it");
                    }
                }
            }));

            // Add cancel button
            alertController.AddAction(UIAlertAction.Create("Cancel", UIAlertActionStyle.Cancel, null));

            PresentViewController(alertController, true, () => { keyboardManagedElsewhere = false; });
        }

        protected void UpdateLabels()
        {
            AddLinkButton.SetTitle((string.IsNullOrWhiteSpace(chosenLink)) ?
                                   "Add an External Link" :
                                   "Edit Link", UIControlState.Normal);

            AddImageButton.SetTitle((string.IsNullOrWhiteSpace(currentImagePath + previousImage)) ?
                                    "Add an Accompanying Image (optional)" :
                                   "Change Image", UIControlState.Normal);

        }

        protected override void FinishButton_TouchUpInside(object sender, EventArgs e)
        {
            if (UpdateBasicTask())
            {

                if (string.IsNullOrWhiteSpace(currentImagePath))
                {
                    currentImagePath = previousImage;
                }
                else if (!string.IsNullOrWhiteSpace(previousImage))
                {
                    // new image replaces old one, delete the previous image
                    File.Delete(AppUtils.GetPathForLocalFile(previousImage));
                }

                string imgUrl = (string.IsNullOrWhiteSpace(currentImagePath)) ? "" : Path.Combine(Directory.GetParent(currentImagePath).Name, Path.GetFileName(currentImagePath));

                AdditionalInfoData data = new AdditionalInfoData
                {
                    ImageUrl = imgUrl,
                    ExternalUrl = chosenLink
                };

                thisTask.JsonData = JsonConvert.SerializeObject(data);


                UpdateActivity();
                Unwind();
            }
        }
    }
}
